# Generated by Django 5.2.4 on 2025-08-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_chatfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
