# Generated by Django 5.2.4 on 2025-08-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0003_chatsession_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfeedback',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chatbot_app.chatmessage'),
        ),
    ]
