# Generated by Django 5.2.4 on 2025-08-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0006_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
    ]
